C++ = c++
C++_FLAGS = -Wall -Wextra -Werror -std=c++98

INFILES = 	main.cpp\
			RPN.cpp

OBJFILES = $(INFILES:.cpp=.o)

NAME = RPN

all: $(NAME)
	@./$(NAME)  "8 9 * 9 - 9 - 9 - 4 - 1 +"

$(NAME):$(OBJFILES)
	$(C++) $(C++_FLAGS) $(OBJFILES) -o $(NAME) 

%.o: %.cpp
	$(C++) $(C++_FLAGS) -c $< -o $@

clean:
	rm -f $(OBJFILES)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re